### PR TITLE
fix right value on update strategy

### PR DESCRIPTION
**Pull request by sawater**
the same as #173

### CODE REVIEW

**Comment by jojohappy** [comment]
@sawater PR #173 has been merged
Close

**Comment by sawater** [comment]
更新的有修复吗？

**Comment by laiwei** [comment]
@sawater #173 中已经修复了，有问题，请reopen。

**Comment by sawater** [comment]
https://github.com/open-falcon/falcon-plus/blob/1d89dc079aadc3f8044013f2b965fe078e093fa1/modules/api/app/controller/strategy/strategy_controller.go#L138

**Pull request merged**
