### PR TITLE
 fix response format of 'Aggregator list of hostgroup' API

### PR DESCRIPTION
**Pull request by danieldai**
fix response format of 'Aggregator list of hostgroup' API and return template on template update API

### CODE REVIEW

**Comment by laiwei** [comment]
there is no need to return the template object after updating. @danieldai

**Comment by danieldai** [comment]
OK. got it. I will remove the commit dc6b7f5

**Comment by danieldai** [comment]
@laiwei I have the remove the commit that changes the template updating API, just left the fix to doc of response format of 'Aggregator list of hostgroup' API

**Comment by hitripod** [comment]
What's wrong with the original format?

**Comment by danieldai** [comment]
@hitripod Please have look at the code around https://github.com/open-falcon/falcon-plus/blob/9ef418d90b2817b12ecd25651b2c1360983fd1f0/modules/api/app/controller/host/aggreator_controller.go#L75

Current document says the API return a json array, but in fact, it return a mapping, according to the code

**Comment by danieldai** [comment]
@laiwei @hitripod have you check the API document and the corresponding API implementation I mentioned in my previous comment, is this patch necessary or not?

**Comment by hitripod** [comment]
I don't think this PR is necessary. 
API Endpoint: http://api.open-falcon.org/#/aggreator_of_hostgroup

**Comment by danieldai** [comment]
@hitripod I‘m integrating falcon-plus with another system; The API is not returning in the format described in the document. which is saying the document is totally misleading.

Actually, response format is:
```{
  "hostgroup": "test_group",
  "aggregators": [
      {
        "id": 13,
        "grp_id": 343,
        "numerator": "$(cpu.idle)",
        "denominator": "2",
        "endpoint": "testenp",
        "metric": "test.idle",
        "tags": "",
        "ds_type": "GAUGE",
        "step": 60,
        "creator": "root"
      },
      {
        "id": 14,
        "grp_id": 343,
        "numerator": "$(cpu.idle)",
        "denominator": "2",
        "endpoint": "testenp",
        "metric": "test.idle",
        "tags": "",
        "ds_type": "GAUGE",
        "step": 60,
        "creator": "root"
      }]
}
```
instead of
```
[
  {
    "id": 13,
    "grp_id": 343,
    "numerator": "$(cpu.idle)",
    "denominator": "2",
    "endpoint": "testenp",
    "metric": "test.idle",
    "tags": "",
    "ds_type": "GAUGE",
    "step": 60,
    "creator": "root"
  },
  {
    "id": 14,
    "grp_id": 343,
    "numerator": "$(cpu.idle)",
    "denominator": "2",
    "endpoint": "testenp",
    "metric": "test.idle",
    "tags": "",
    "ds_type": "GAUGE",
    "step": 60,
    "creator": "root"
  }
]
```

**Pull request merged**
